#!/bin/zsh

new-post() {
	read "?Title: " title
	escaped=$(sed 's/ /-/g' <<< $title)
	postfile="drafts/$escaped.html"

	if [[ -f $postfile ]]; then
		echo "Post with this name already exists"
		exit
	fi

	cat << EOF > metadata/$title
title=$title
EOF

	touch $postfile
	edit $escaped.html
}

update() {
	ls drafts \
		| fzf \
		| read post
	edit $post
}

edit() {
	postfile=$1
	$EDITOR drafts/$postfile

	read "?Is this post ready for rendering? (y/N): " ans

	if [[ ans == [yY] ]]; then
		ln -sf drafts/$postfile published/$postfile
	fi
}

render-post() {
	echo "Started rendering $1"
	template=templates/post.template.html
	# Replace all \ with \\. Otherwise awk gets confused when post includes an \
	content=$(sed < published/$1.html 's/\\/\\\\/g')

	awk < metadata/$1 -F'=' '/title/{print $2}' | read title

	awk -v title=$title -v content=$content < $template '/<-- TITLE -->/{print title} /<-- POST -->/{print content} !/<--/{print}' > html/posts/$1.html
	echo "Done rendering $1"
}

render-list() {
	echo "Started rendering post list"
	template=templates/list.template.html

	local list=""

	for file in published/*; do
		basename $file .html | read filename
		awk -F'=' -v file=$filename \
			'/title/{print "<li><a href=\"/posts/"file".html\">"$2"</a></li>"}' \
			metadata/$filename | read entry
		list="$list$entry\n"
	done

	awk -v list=$list < $template '/<!-- POSTS -->/{print list} !/<!--/{print}' > html/list.html

	echo "Done rendering post list"
}

render-rss() {
	echo "Started rendering RSS"
	template=templates/rss.template.xml

	local list=""

	for file in published/*; do
		basename $file .html | read filename
		link="https://blog.draganczuk.me/posts/$filename.html"
		awk -F'=' -v link=$link \
			'/title/{print "<item><title>"$2"</title><link>"link"</link><guid>"link"</guid><description>"$2"</description></item>"}' \
			metadata/$filename | read entry
		list="$list$entry\n"
	done

	awk -v list=$list < $template '/<!-- LIST -->/{print list} !/<!--/{print}' > html/rss.xml

	echo "Done rendering RSS"
}

render() {
	for post in published/*.html; do
		render-post $(basename $post .html)
	done

	render-list
	render-rss

}

echo "New\nEdit\nRender" \
	| fzf \
	| read choice

case $choice in
	New)
		new-post;;
	Edit)
		update;;
	Render)
		render;;
esac
