version: '3'
services:
    blog:
        build:
            context: .
        container_name: blog
        ports:
            - 80:80
        # networks:
        #     - proxy
        restart: ${RESTART}
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.blog.entrypoints=https"
          - "traefik.http.routers.blog.rule=Host(`blog.draganczuk.me`)"
          - "traefik.http.routers.blog.tls=true"
          - "traefik.http.services.blog.loadbalancer.server.port=80"
          - "traefik.docker.network=proxy"

# networks:
#     proxy:
#         external: true
